### PR TITLE
Upgrade Project to {N} 4.x

### PR DESCRIPTION
**Pull request by shiv19**
This PR contains the tasks mentioned in #147 

Let's not merge this until this PR gets merged
https://github.com/NativeScript/NativeScript/pull/6124

### CODE REVIEW

**Comment by shiv19** [comment]
@nikolasdas the mentioned PR is merged, but it is not officially released it.
It will come with NativeScript 5.0 :)

**Comment by nikolasdas** [comment]
@shiv19 Oh I see, thank you :)

**Comment by oliverpool** [comment]
@shiv19 NativeScript 5.0 has been released for some time now :-)

**Comment by shiv19** [comment]
@oliverpool thanks for the reminder :)

@NathanWalker Can we merge this please :)

**Comment by NathanWalker** [comment]
Permissions were reset so I can’t :(
@vakrilov @etabakov ?

**Comment by shiv19** [comment]
Oh okay :(

**Comment by NathanWalker** [comment]
Merging and will fix linting afterwards.

**Pull request merged**
