### PR TITLE
feat(Skins): ActionBar skins with theme'd sets

### PR DESCRIPTION
**Pull request by NathanWalker**
closes https://github.com/NativeScript/theme/issues/85

@myninka I have a nice way to handle the ActionBar skins.
You can see how the skins are implemented here:
https://github.com/NativeScript/theme/tree/skins/app/theme-core-scss/themes/core/skins
Different .css files are generated for the skins, for example, here is how the `sky` theme can be implemented:
https://github.com/NativeScript/theme/blob/skins/app/demo-styles/sky.ios.scss
https://github.com/NativeScript/theme/blob/skins/app/demo-styles/sky.android.scss

We can potentially distribute these css compiled skins with this theme as options and document how to use them. I see 3 ways to go with how we want to distribute these:

1. Compile theme sets for each theme (would be about 22 css files [11 light, 11 dark]) and publish with the theme.
2. Don't distribute the compiled css for the skins. Just the compiled core theme (light/dark) itself and let the user setup the skins via `SASS`. So just the `SASS` files of the skins and document how user's can import these `SASS` skins to build from them.
3. Completely remove the skins from this *core* theme and distribute as individual npm packages for users to install at their own choice. Much like this is installed via `npm i nativescript-theme-core`, we could publish 11 different theme sets for each skin, `nativescript-theme-sky`, `nativescript-theme-orange`, `nativescript-theme-lemon`, etc.

Here's a view of how things are implemented now in the demo app to try these out:
skins

/cc @valentinstoychev @NathanaelA @jlooper @tjvantoll @bradmartin @sitefinitysteve @triniwiz @TheOriginalJosh

### CODE REVIEW

**Comment by mikebranstein** [comment]
I think themes should have a core set of non-compiled skins, with a method to provide custom skins. 

Option 2 feels right to me. It provides others with explicit examples of what needs to be done to extend with their own skins in the core package. I also don't have to pull in yet another package just to get a skin. 

I wouldn't want all of the skin to be included in the app automatically. Instead, I'd want a compiler/build setting in place to indicate which skin(s) to include in the built app.

**Comment by NathanaelA** [comment]
2 feels wrong for the vast majority of people.  Most people don't use Sass.   So requiring it doesn't help spread adoption of using the theme in my opinion.   

I think number 1 is the best way; and just document that to use the theme is a require('nativescript-theme-core/red.css') or whatever is needed.  Css files are typically pretty small so wasting the space for the 22 css files in a non-issue in my book...

**Comment by NathanWalker** [comment]
@mikebranstein We discussed this and I like your thought, however we want to stay away from making `SASS` required to use some of what you get with the theme.

Turns out the compiled css files are *indeed* very small (25k each), don't induce any maintenance burden, and don't affect the end user since they can pick/choose what they want to use and exclude the rest.

For example, for a pure CSS user, this is how they would use the `sky` skin:

```
@import 'nativescript-theme-core/css/sky.css';
```

They can optionally use their own custom sass setup which will be documented on the themes section of the docs and follow this guideline:
https://github.com/NativeScript/theme/blob/91e55ac75963d0153bef21f56dfa3ca0c8af7755/app/demo-styles/sky.ios.scss
However the paths will be slightly different when using from the npm installed package of which @tjvantoll is aware and will document them correctly.

If all sounds good to core team, I will merge this. Please thumbs up if you are ok with this.

**Comment by tjvantoll** [comment]
Ping @hdeshev @hshristov @atanasovg. Any concerns with the approach @NathanWalker spells out above for adding more color schemes to the core theme?

**Comment by mikebranstein** [comment]
@NathanWalker that's cool. We'll get everyone on SASS one day ;-) It probably best that another dependency isn't introduced right now.

**Pull request merged**
