### PR TITLE
Fix Script from TNS Buggy install behavior while installing TNS template

### PR DESCRIPTION
**Pull request by NathanaelA**

### CODE REVIEW

**Comment by NathanaelA** [comment]
Fixed #95

**Comment by NathanWalker** [comment]
Thank you!

**Comment by NathanWalker** [comment]
@NathanaelA Unfortunately this fix did not work :(
Just published `0.1.4` with this fix and the duplicate folder is still created.
To repro:
```
tns create theme-test --template https://github.com/NativeScript/template-hello-world-ng.git
```
Notice `0.1.4` will be installed but the `app` folder will contain another `app` folder inside with dupe files.

**Comment by vchimev** [comment]
@NathanaelA,

what bug are you referring to? Could you please log it the CLI repo in order to investigate it?

Thank you!

**Comment by NathanaelA** [comment]
@NathanWalker 
I just copied and pasted your command line into a command prompt; then here is what I have:
capture1
capture2

I do not have a duplicated app folder.  Are you sure when you tested it; that it still wasn't hitting the old theme version?

**Comment by NathanaelA** [comment]
@vchimev - there already is a "feature" request in the cli since about 2.0 time frame I think.   If it gets done, then it would allow this process to be a lot smoother.     Nathan Walker is aware of it already because he heard me complain about it totally destroying my tns-template-plugin several months back, and so I had to actually drop the idea of actually having a "template" for plugins because TNS makes some **assumptions** and if your stuff doesn't fall inside that assumption it destroys it...  

I just was letting Nathan know why the script broke in this specific case.   ;-)

**Comment by NathanaelA** [comment]
#101 fixes it for mac also...  Silly macs...

**Pull request merged**
