### PR TITLE
fix(bootstrap): Remove the second definition of $font-size, fix…

### PR DESCRIPTION
**Pull request by bundyo**

### CODE REVIEW

**Comment by MartoYankov** [comment]
Is this whole construct really necessary? When I use `t-XX` I expect my font size to be exactly XX regardless of the global `$font-size` variable.

**Comment by bundyo** [comment]
I was actually thinking the same. Probably this is a mechanism in Bootstrap to be able to change all sizes in your app by just changing the $font-size. Something like building your site on em/rem units, but without them. :)

We can remove it along with Bootstrap when the time comes.

**Comment by MartoYankov** [comment]
I don't think removing bootstrap will be anytime soon, so I'm all for hard-coding these in favor of a simpler and more maintainable code for the time being.

**Comment by MartoYankov** [comment]
Also, please change the PR title to fit the [semantic pull request](https://github.com/probot/semantic-pull-requests) guidelines. These are important for our release notes.

**Pull request merged**
