### PR TITLE
Fix(npm scripts): remove postinstall and uninstall scripts

### LINKED ISSUE #95: Duplicate css folder
Hi, All!

I just gave a try to the default template by:

```
tns create appJS --template https://github.com/NativeScript/template-hello-world.git#master
```

and noticed that the project that was created has a duplicate of the _css_ folder:

screen shot 2016-10-26 at 4 57 36 pm

Any clue why does this happen?

@NathanWalker @tjvantoll

### PR DESCRIPTION
**Pull request by sis0k0**
The postinstall and uninstall scripts are no longer needed after change
NativeScript/NativeScript#3035 in `tns-core-modules`.
The above change enables shorthand css import from `tns_modules`.

Closes #95

### CODE REVIEW

**Comment by vchimev** [comment]
Hey @NathanWalker,

what is your opinion here? We would like to merge this pull request and update the templates for 2.4.0.

Thanks!

**Comment by NathanWalker** [comment]
@vchimev we will give it a go. If things don't work out we may need to bring post install back. I'll publish an update tomorrow morning with this.
Thank you @sis0k0 !!

**Comment by NathanWalker** [comment]
@sis0k0 @vchimev `0.2.0` has been published with this now 👍

**Comment by vchimev** [comment]
Templates updated to `0.2.1`: https://github.com/NativeScript/template-hello-world/commit/829ade214fda3f9619ab243416e392b2ab2adee7.

**Pull request merged**
